thehyve/dntp-portal

bower.json
src/main/java/business/controllers/PasswordController.java
src/main/java/business/controllers/ProfileController.java
src/main/java/business/models/NewPasswordRequest.java
src/main/java/business/models/NewPasswordRequestRepository.java
src/main/java/business/models/User.java
src/main/java/business/models/UserRepository.java
src/main/java/business/representation/EmailRepresentation.java
src/main/java/business/representation/NewPasswordRepresentation.java
src/main/java/business/representation/PasswordChangeRepresentation.java
src/main/java/business/representation/ProfileRepresentation.java
src/main/java/business/security/DefaultUsers.java
src/main/java/business/security/HttpSecurityConfiguration.java
src/main/java/business/security/RoleController.java
src/main/java/business/security/SecureTokenGenerator.java
src/main/java/business/security/SecurityConfiguration.java
src/main/java/business/security/UserAuthenticationToken.java
src/main/java/business/security/UserController.java
src/main/resources/static/app/components/forgot-password/ForgotPasswordController.js
src/main/resources/static/app/components/forgot-password/ResetPasswordController.js
src/main/resources/static/app/components/forgot-password/forgot-password.html
src/main/resources/static/app/components/forgot-password/reset-password.html
src/main/resources/static/app/components/profile/PasswordController.js
src/main/resources/static/app/components/profile/ProfileController.js
src/main/resources/static/app/components/profile/password.html
src/main/resources/static/app/components/profile/profile.html
src/main/resources/static/app/processapp.js
src/main/resources/static/index.html
src/main/resources/static/login.html
src/main/resources/static/messages/messages_nl.js

Backend almost ready (sending email doesn't work yet)
Frontend works, but the translations are not complete, there is some
code repetition and error handling is poor.

User profile, password change and recovery

---

.gitignore
README.md
build.gradle

To make it possible to build project with Gradle.

Gradle version

---

src/main/resources/static/app/components/registration/registration.html
src/main/resources/static/messages/messages_nl.js

Fix password validation and rewording lab label.

---

bower.json
src/main/resources/static/app/processapp.js
src/main/resources/static/app/request/RequestController.js
src/main/resources/static/app/request/editrequest.html
src/main/resources/static/index.html

To enable 'popover' as component to be used as tooltip for input texts that user needs more information about it.

Placeholder for tooltip

---

e2e/login.po.js
e2e/main.spec.js

Renamed main.po to login.po
Login is now done before each test

Protractor now uses local running server (instead of static pages)

---

e2e/main.spec.js
e2e/nav.po.js
src/main/resources/static/app/components/navbar/navbar.html

logout is now automatically perfomed in the end of each test

Added initial nav.po

---

src/main/java/business/representation/LabRequestRepresentation.java
src/main/java/business/services/LabRequestService.java
src/main/resources/static/app/components/navbar/NavigationController.js
src/main/resources/static/app/components/navbar/navbar.html
src/main/resources/static/app/lab-request/LabRequestController.js
src/main/resources/static/app/lab-request/LabRequestFactory.js
src/main/resources/static/app/lab-request/lab-request.html
src/main/resources/static/app/lab-request/lab-requests.html
src/main/resources/static/app/login/LoginController.js
src/main/resources/static/app/processapp.js
src/main/resources/static/app/request/RequestServices.js
src/main/resources/static/app/request/SelectionController.js
src/main/resources/static/index.html
src/main/resources/static/messages/messages_en.js
src/main/resources/static/messages/messages_nl.js

Mostly about implementation of Lab Request overview and details

Lab Request Overview & Details

---

e2e/documentation/readme.md
e2e/forgot-password.feature
e2e/login.feature
e2e/manage-requests.feature.unimplemented
e2e/new-request.feature
e2e/steps/stepDefinitions.js
e2e/util.js
src/main/resources/static/app/forgot-password/forgot-password.html
src/main/resources/static/app/request/edit-request.html

An important change is that I added a documentation file (in Markdown format) explaining what is currently possible to do in the tests.

Cucumber improvements

---

src/main/java/business/controllers/RequestController.java
src/main/java/business/controllers/RequestListRepresentationComparator.java
src/main/java/business/models/RequestPropertiesRepository.java
src/main/java/business/services/RequestNumberService.java
src/main/java/business/services/RequestService.java
src/main/resources/static/app/components/sidebar/sidebar-template.html
src/main/resources/static/app/request/RequestController.js
src/main/resources/static/app/request/RequestServices.js
src/main/resources/static/app/request/requests.html

- Autonumber old requests at startup;
- Sort requests based on request number;
- Added 'pull-right' to badges in sidebar.

Autonumbering old requests; proper sorting of requests.

---

src/main/resources/static/app/admin/agreementformtemplate/AgreementFormTemplateController.js
src/main/resources/static/app/admin/agreementformtemplate/edit.html
src/main/resources/static/app/request/RequestController.js
src/main/resources/static/app/request/agreementform.html
src/main/resources/static/app/services/AgreementFormService.js
src/main/resources/static/css/index.css

Preview is now automatically updated after inserting a variable.

Agreementform replacevariables

---

README.md
src/main/java/business/controllers/LabController.java
src/main/java/business/controllers/LabRequestController.java
src/main/java/business/controllers/RequestController.java
src/main/java/business/controllers/RequestListRepresentationComparator.java
src/main/java/business/controllers/SelectionController.java
src/main/java/business/models/Lab.java
src/main/java/business/models/LabRequest.java
src/main/java/business/models/LabRequestRepository.java
src/main/java/business/models/Role.java
src/main/java/business/models/User.java
src/main/java/business/representation/ProfileRepresentation.java
src/main/java/business/security/CustomPermissionEvaluator.java
src/main/java/business/security/CustomPermissionService.java
src/main/java/business/security/DefaultRoles.java
src/main/java/business/security/DefaultRolesUsersLabs.java
src/main/java/business/services/LabRequestService.java
src/main/java/business/services/RequestService.java

@rnugraha Backend code for "hub assistance enabled" field.

Add "hub assistance enable" field to labs.

---

src/main/resources/static/app/components/navbar/NavigationController.js
src/main/resources/static/app/components/navbar/navbar.html
src/main/resources/static/app/components/sidebar/LabRequestsSidebarDirective.js
src/main/resources/static/app/components/sidebar/SidebarDirective.js
src/main/resources/static/app/components/sidebar/lab-requests-sidebar-template.html
src/main/resources/static/app/components/sidebar/sidebar-template.html
src/main/resources/static/app/interceptors/ResponseInterceptor.js
src/main/resources/static/app/lab-request/LabRequestController.js
src/main/resources/static/app/lab-request/LabRequestServices.js
src/main/resources/static/app/lab-request/lab-requests.html
src/main/resources/static/app/login/LoginController.js
src/main/resources/static/app/processapp.js
src/main/resources/static/app/request/LoadTestController.js
src/main/resources/static/app/request/RequestController.js
src/main/resources/static/app/request/edit-request.html
src/main/resources/static/app/request/requests.html
src/main/resources/static/app/services/FilterService.js
src/main/resources/static/app/services/RequestServices.js
src/main/resources/static/css/index.css
src/main/resources/static/index.html
src/main/resources/static/messages/README.md
src/main/resources/static/messages/messages_en.js
src/main/resources/static/messages/messages_nl.js
src/main/resources/static/messages/msg2tsv.js

- Status overview for requests and lab requests;
- Interceptor for error handling;
- Updated some login/logout functionality.

Add status overview in sidebar.

---

src/main/java/business/controllers/LabController.java
src/main/java/business/controllers/LabProfileController.java
src/main/java/business/controllers/ProfileController.java
src/main/java/business/exceptions/EmailAddressInvalid.java
src/main/java/business/models/Lab.java
src/main/java/business/models/LabRepository.java
src/main/java/business/security/DefaultRolesUsersLabs.java
src/main/java/business/services/ExcerptListService.java
src/main/java/business/services/LabRequestService.java
src/main/java/business/services/LabService.java
src/main/java/business/services/MailService.java
src/main/java/business/services/UserService.java
src/main/resources/static/app/admin/lab/AdminLabController.js
src/main/resources/static/app/admin/lab/editlab.html
src/main/resources/static/app/admin/lab/labs.html
src/main/resources/static/app/admin/user/AdminUserController.js
src/main/resources/static/app/admin/user/users.html
src/main/resources/static/app/interceptors/ResponseInterceptor.js
src/main/resources/static/app/lab-request/LabRequestController.js
src/main/resources/static/app/lab-request/pa-numbers.html
src/main/resources/static/app/lab-request/samples.html
src/main/resources/static/app/lab/MyLabController.js
src/main/resources/static/app/lab/my-lab.html
src/test/java/business/LargerExcerptListTests.java
src/test/java/business/ProcessControllerTests.java
src/test/java/business/SelectionControllerTests.java
src/test/java/business/SmallExcerptListTests.java

- Enable multiple email addresses per lab.
- Enable migrating lab mail address to list.

Multiple lab email addresses

---

src/main/java/business/services/MailService.java
src/main/resources/static/app/admin/user/edituser.html
src/main/resources/static/app/request/approvals.html
src/main/resources/static/app/request/edit-request.html
src/main/resources/static/app/request/request-review.html
src/main/resources/static/app/request/selection.html
src/main/resources/static/app/request/upload-file.html
src/main/resources/static/css/index.css

- Adjust request new password wording in email template
- Change alignment of selected labs from center to left when creating hub user
- h4 instead of h3 for sub headers under h3

Improvement create hubuser

---

karma.conf.js
src/main/resources/static/app/admin/lab/labs.html
src/main/resources/static/app/admin/user/edituser.html
src/main/resources/static/app/components/specialism/SpecialismDirective.js
src/main/resources/static/app/components/specialism/SpecialismDirective.spec.js
src/main/resources/static/app/components/specialism/specialism-template.html
src/main/resources/static/app/processapp.js
src/main/resources/static/app/registration/registration.html
src/main/resources/static/index.html
src/main/resources/static/messages/messages_en.js
src/main/resources/static/messages/messages_nl.js

- Create specialism directive
- To use it in edit user and registration form
- validation
- unit testing

Add specialism def

---

src/main/resources/static/app/lab-request/edit-lab-request.html

lab/palga/hub users should not be able to update PA report status in lab request when it has been rejected

Rejected lab request bug

---

src/main/java/business/models/ContactData.java
src/main/java/business/services/PaNumberService.java
src/main/java/business/services/RequestFormService.java

@gijskant Even wat comments.
Ik heb null checks toegevoegd voordat de lowercase transformatie wordt gedaan. Waarschijnlijk overkill aangezien de velden in iedergeval in de frontend al geforceerd worden.
@Valid validatie wordt niet gedaan bij de PUT van een request (@RequestController:248) dus vandaar de conditional.
Dit is uiteraard nog een toevoeging die gedaan kan worden.
Voor ticket DNTPSD-111 (toevoegen van de kolommen in de Download PA numbers functionaliteit) is de commit ook toegevoegd.
Gaarne even controleren :)

Dntpsd 105

---

src/main/resources/static/app/forgot-password/forgot-password.html
src/main/resources/static/app/login/login.html
src/main/resources/static/app/registration/thank-you.html
src/main/resources/static/css/index.css

[DNTPSD-117] Fields hidden / blank pages after landing page restyling. 
Pressing return in the login form now fires a submit event.

Hotfix 12012017 - DNTPSD-117

---

src/main/resources/static/app/forgot-password/reset-password.html
src/main/resources/static/css/index.css

Reset password layout

---

src/main/resources/static/app/activation/activate.html
src/main/resources/static/css/index.css

small css fix to show formerly hidden div

Fixing activation message placement DNTP-532

---

src/main/java/business/controllers/CommentController.java

Fixes [DNTP-536](https://jira.thehyve.nl/browse/DNTP-536).

Fix updates of lab request comments.

---

src/main/java/business/services/UserService.java

Clear cache when saving user data

clean cache

---

src/main/resources/static/app/components/sidebar/lab-requests-sidebar-template.html
src/main/resources/static/app/lab-request/LabRequestController.js
src/main/resources/static/app/lab-request/lab-requests.html

reset filters for statuses when clicking on sidebar for labrequests just like for requests.

Dntpsd 132 reset filter

---

src/main/java/business/controllers/SelectionController.java
src/main/java/business/services/RequestFormService.java
src/main/resources/ehcache.xml
src/main/resources/static/app/request/edit-request.html
src/main/resources/static/css/index.css

- Fixes [DNTP-608](https://jira.thehyve.nl/browse/DNTP-608).
- Fixes styling of the edit request buttons.

Dntp 608 fix status caching

---

src/main/java/business/controllers/LabRequestController.java
src/main/java/business/services/LabRequestService.java

This fixed it for me locally, but I'm not sure if this is a great solution. Thoughts? @gijskant ?

Create new task when claiming if old one is missing

---

src/main/java/business/ErrorMessage.java
src/main/resources/static/app/lab-request/LabRequestController.js
src/main/resources/static/app/lab-request/pa-numbers.html
src/main/resources/static/app/lab-request/samples.html
src/main/resources/static/messages/messages_en.js
src/main/resources/static/messages/messages_nl.js

Fixes [DNTPSD-155](https://jira.thehyve.nl/browse/DNTPSD-155).

Fix recall mail link

---

src/main/resources/static/app/request/edit-request.html
src/main/resources/static/app/request/request-contents.html

Related ticket: [DNTP-623](https://jira.thehyve.nl/browse/DNTP-623)

Move "Data linkage" section of the request above "Billing address"

---

README.md
e2e/pages/requests.js
e2e/scenario_additional_request.feature
e2e/steps/stepDefinitions.js
e2e/util.js
src/main/java/business/controllers/RequestController.java
src/main/java/business/models/RequestProperties.java
src/main/java/business/models/RequestPropertiesRepository.java
src/main/java/business/models/User.java
src/main/java/business/representation/RequestListRepresentation.java
src/main/java/business/security/DefaultRolesUsersLabs.java
src/main/java/business/services/LabRequestQueryService.java
src/main/java/business/services/RequestFormService.java
src/main/java/business/services/RequestPropertiesService.java
src/main/java/business/services/RequestService.java
src/main/java/business/services/UserService.java
src/main/resources/static/app/request/requests.html
src/main/resources/static/messages/messages_nl.js
src/test/java/business/AbstractSelectionControllerTests.java
src/test/java/business/RequestControllerTests.java

Display last Palga advisor if current one not set [(DNTP-629)](https://jira.thehyve.nl/browse/DNTP-629)

Add last assignee to the request properites

---

e2e/scenario_skip_scientific_council.feature
e2e/steps/stepDefinitions.js
src/main/java/business/representation/RequestRepresentation.java
src/main/java/business/services/RequestFormService.java
src/main/resources/static/app/request/RequestController.js
src/main/resources/static/app/request/edit-request.html
src/main/resources/static/app/request/request-contents.html
src/main/resources/static/app/request/request-review.html
src/main/resources/static/css/index.css
src/main/resources/static/messages/messages_nl.js
src/test/java/business/AbstractSelectionControllerTests.java
src/test/java/business/RequestControllerTests.java

[DNTP-628](https://jira.thehyve.nl/browse/DNTP-628)

Add possibility to skip agreements when skipping scientific council

---

README.md
e2e/scenario_additional_request.feature
e2e/scenario_complete_happy_request.feature
e2e/scenario_hub_user.feature
e2e/scenario_reopen_request.feature
e2e/scenario_skip_scientific_council.feature
e2e/scenario_up_to_approval_lab_request.feature
src/main/java/business/models/RequestProperties.java
src/main/java/business/representation/RequestListRepresentation.java
src/main/java/business/representation/RequestRepresentation.java
src/main/java/business/services/LabRequestExportService.java
src/main/java/business/services/RequestExportService.java
src/main/java/business/services/RequestFormService.java
src/main/resources/static/app/lab-request/LabRequestController.js
src/main/resources/static/app/lab-request/edit-lab-request.html
src/main/resources/static/app/lab-request/lab-request-contents.html
src/main/resources/static/app/lab-request/lab-requests.html
src/main/resources/static/app/lab-request/pa-numbers.html
src/main/resources/static/app/request/RequestController.js
src/main/resources/static/app/request/edit-request.html
src/main/resources/static/app/request/request-contents.html
src/main/resources/static/app/request/request-review.html
src/main/resources/static/app/request/requests.html
src/main/resources/static/app/request/upload-file.html
src/main/resources/static/app/services/FilterService.js
src/main/resources/static/app/services/RequestServices.js
src/main/resources/static/messages/messages_en.js
src/main/resources/static/messages/messages_nl.js
src/test/java/business/AbstractSelectionControllerTests.java
src/test/java/business/LabRequestExportControllerTests.java

Related ticket: [DNTP-627](https://jira.thehyve.nl/browse/DNTP-627)

Replace the "PA materiaal" option with 3 new options

---

README.md

Related ticket: [DNTP-632](https://jira.thehyve.nl/browse/DNTP-632)

Add migration script for new PA materials options

---

src/main/webapp/app/services/RequestTypeService.js
src/main/webapp/messages/messages_en.js
src/main/webapp/messages/messages_nl.js

Fixes [DNTP-630](https://jira.thehyve.nl/browse/DNTP-630)

Fix translations for request type
